package pt.tecnico.grpc.server;

/* these imported classes are generated by the hello-world-server contract */
import pt.tecnico.grpc.Banking.*;
import pt.tecnico.grpc.BankingServiceGrpc;

import io.grpc.stub.StreamObserver;

public class BankingServiceImpl extends BankingServiceGrpc.BankingServiceImplBase {
	private Bank bank = new Bank();

	@Override
	public void register(RegisterRequest request, StreamObserver<RegisterResponse> responseObserver) {
		bank.register(request.getClient(), request.getBalance());

		responseObserver.onNext(RegisterResponse.getDefaultInstance());
		responseObserver.onCompleted();
	}

	@Override
	public void consult(ConsultRequest request, StreamObserver<ConsultResponse> responseObserver) {
		ConsultResponse response = bank.getBalance(request.getClient());

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}
}
